[appservers]
178.62.88.196 name=partup-production-london1-04
46.101.10.191 name=partup-production-london1-05
178.62.125.185 name=partup-production-london1-06
46.101.1.145 name=partup-production-london1-07

[cronservers]
46.101.33.171 name=partup-cron-production-london1-02

[production:children]
appservers
cronservers

[production:vars]
server_environment_name=production
